<?php include 'tpl/header.php' ?>

<nav class="extra-nav py-20">
    <div class="container">
        <div class="row no-gutters align-items-md-center flex-column flex-md-row">
            <div>
                <ol class="breadcrumb mb-lg-0">
                    <li class="breadcrumb-item"><a href="#" class="text-dark">Home</a></li>
                    <li class="breadcrumb-item active">Terms and Conditions</li>
                </ol>
            </div>

            <div class="ml-lg-auto d-flex flex-column flex-md-row">
                <a href="/about.php" class="extra-nav-link">About Us</a>
                <a href="/policy.php" class="extra-nav-link">Privacy Policy</a>
                <a href="/terms.php" class="extra-nav-link active">Terms and Conditions</a>

                <a href="javascript:history.back()" class="extra-nav-link extra-nav-link-special d-none d-lg-inline"><span class="fa fa-angle-left large mr-2"></span> Назад</a>
            </div>
        </div>
    </div>
</nav>

<main>
    <section class="py-40 py-md-60">
        <div class="container">
            <h2 class="mb-40 text-center">Terms and Conditions</h2>

            <h3 class="text-center">Limited Warranty</h3>
            <p>InTouch warrants that handsets are free from defects in material and workmanship under normal use and service for the period commencing upon the date of purchase by the first consumer purchaser and continuing for 1 year from the purchase date.</p>
            <p>This Warranty is conditioned upon proper use of the Product. This Warranty does not cover: (a) defects or damage resulting from accident, misuse, abnormal use, abnormal conditions, improper storage, exposure to liquid, moisture, dampness, sand or dirt, neglect, or unusual physical, electrical or electromechanical stress; (b) scratches, dents and cosmetic damage, unless caused by InTouch; (c) defects or damage resulting from excessive force or use of a metallic object when pressing on a touch screen; (d) equipment that has the serial number or the enhancement data code removed, defaced, damaged, altered or made illegible; (e) ordinary wear and tear; (f) defects or damage resulting from the use of Product in conjunction or connection with accessories, products, or ancillary/peripheral equipment not furnished or approved by the equipment manufacturer (g) defects or damage resulting from improper testing, operation, maintenance, installation, service, or adjustment not furnished or approved by the manufacturer; (h) defects or damage resulting from external causes such as collision with an object, fire, flooding, dirt, windstorm, lightning, earthquake, exposure to weather conditions, theft, blown fuse, or improper use of any electrical source; (i) defects or damage resulting from cellular signal reception or transmission, or viruses or other software problems introduced into the Product.. This Limited Warranty covers batteries only if battery capacity falls below 80% of rated capacity or the battery leaks, and this Limited Warranty does not cover any battery if (i) the battery has been charged by a battery charger not specified or approved by the manufacturer for charging the battery; (ii) any of the seals on the battery are broken or show evidence of tampering; or (iii) the battery has been used in equipment other than the phone it was purchased with.</p>
            <p>During the applicable warranty period, provided the Product is returned in accordance with the terms of this Limited Warranty, InTouch will repair or replace the Product, at InTouch’s sole option, without charge. InTouch may, at InTouch's sole option, use rebuilt, reconditioned, or new parts or components when repairing any Product, or may replace the Product with a rebuilt, reconditioned or new Product. Repaired/replaced Products will be warranted for a period equal to the remainder of the original Limited Warranty on the original Product or for ninety (90) days, whichever is longer. All replaced Products, parts, components, boards and equipment shall become the property of InTouch. Except to any extent expressly allowed by applicable law, transfer or assignment of this Limited Warranty is prohibited.</p>
            <p>THIS LIMITED WARRANTY SETS OUT THE FULL EXTENT OF InTouch'S RESPONSIBILITIES, AND THE EXCLUSIVE REMEDY REGARDING THE PRODUCTS. ALL IMPLIED WARRANTIES, INCLUDING WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, ARE LIMITED TO THE DURATION OF THIS LIMITED WARRANTY. IN NO EVENT SHALL InTouch BE LIABLE FOR DAMAGES IN EXCESS OF THE PURCHASE PRICE OF THE PRODUCT OR FOR, WITHOUT LIMITATION, COMMERCIAL LOSS OF ANY SORT; LOSS OF USE, TIME, DATA, REPUTATION, OPPORTUNITY, GOODWILL, PROFITS OR SAVINGS; INCONVENIENCE; INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES; OR DAMAGES ARISING FROM THE USE OR INABILITY TO USE THE PRODUCT. SOME STATES AND JURISDICTIONS DO NOT ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, OR THE DISCLAIMER OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATIONS AND DISCLAIMERS MAY NOT APPLY TO YOU.
                <br> InTouch MAKES NO WARRANTIES OR REPRESENTATIONS, EXPRESS OR IMPLIED, STATUTORY OR OTHERWISE, AS TO THE QUALITY, CAPABILITIES, OPERATIONS, PERFORMANCE OR SUITABILITY OF ANY THIRD-PARTY SOFTWARE OR EQUIPMENT USED IN CONJUNCTION WITH THE PRODUCT, OR THE ABILITY TO INTEGRATE ANY SUCH SOFTWARE OR EQUIPMENT WITH THE PRODUCT, WHETHER SUCH THIRD-PARTY SOFTWARE OR EQUIPMENT IS INCLUDED WITH THE PRODUCT DISTRIBUTED BY InTouch OR OTHERWISE. RESPONSIBILITY FOR THE QUALITY, CAPABILITIES, OPERATIONS, PERFORMANCE AND SUITABILITY OF ANY SUCH THIRD-PARTY SOFTWARE OR EQUIPMENT RESTS SOLELY WITH THE USER AND THE DIRECT VENDOR, OWNER OR SUPPLIER OF SUCH THIRD-PARTY SOFTWARE OR EQUIPMENT.</p>
            <p>Nothing in the Product instructions or information shall be construed to create an express warranty of any kind with respect to the Products. No agent, employee, dealer, representative or reseller is authorized to modify or extend this Limited Warranty or to make binding representations or claims, whether in advertising, presentations or otherwise.</p>
            <p>This Limited Warranty gives you specific legal rights, and you may also have other rights that vary from state to state.</p>
            <h3 class="text-center">Cancellation</h3>
            <h4 class="text-center">Voice Only Devices</h4>
            <p>Purchases of voice devices cancelled prior to the device being shipped to customer will be free of charge. Cancellation of purchase after the device has been shipped to the customer; customer will be refunded the purchase price less appropriate shipping fees providing the device is returned unopened in original undamaged packaging.&nbsp; The customer will have one month from the delivery date to return the device or customer will be liable for the full purchase price.&nbsp; Any devices returned within this time period that are deemed by InTouch to have been opened or tampered with in any way will be subject to a restock fee equal to 20% of the purchase price plus shipping fees.</p>
            <h4 class="text-center">Data Devices</h4>
            <p>Purchases of Data/Smartphone devices cancelled prior to the device being shipped to customer will be free of charge provided the data bundle has not been activated with the network, if the data bundle has been activated, customer is liable for the cost of one month of data service.</p>
            <p>Cancellation of purchase after the device has been shipped to the customer, customer will be refunded the purchase price less appropriate shipping fees and one month of data service, providing the device is returned unopened in original undamaged packaging.&nbsp; The customer will have one month from the delivery date to return the device or customer will be liable for the full purchase price.&nbsp; Any devices returned within this time period that are deemed by InTouch to have been opened or tampered with in any way will be subject to an additional restock fee which will be equal to 20% of the purchase price plus shipping fees and data service.</p>
            <p>&nbsp;</p>
            <p>Usage Charges</p>
            <p>1.&nbsp;Subscriber will pay the charges for all usage of the Equipment, including, but not limited to, charges for data, airtime and calls made and received on the Equipment after delivery and any other charges for Service ("Usage Charges") at the usage rates set out on the Website at the time the call is placed. Contact InTouch if usage rates are not available on the Website. InTouch may increase the usage rates at any time, as and when it deems appropriate. Posting of such increases on the Website, shall constitute sufficient notice thereof to Subscriber.</p>
            <p>2.&nbsp;Subscriber will pay for each incoming, outgoing, completed, incomplete or attempted call in full minute increments, with partial minutes rounded to the next full minute, in accordance with standard cellular billing practices.</p>
            <p>3.&nbsp;Subscriber shall pay all Charges invoiced immediately upon generation of a invoice from InTouch. Invoices that remain unpaid after the date of the invoice are delinquent, and Service is subject to immediate suspension or termination. InTouch shall be entitled to charge interest at the rate of 1.5% per month on delinquent accounts. In no event will any late payment fees exceed the highest lawful rate.</p>
            <p>4.&nbsp;Subscriber shall be liable to InTouch for all expenses, including reasonable attorneys’ fees, collection fees and court costs incurred in connection with any collection, repossession or other action brought to enforce InTouch’s rights hereunder.</p>
            <p>5.&nbsp;Subscriber must notify InTouch in writing of any disputes regarding Charges within 30 days of receipt of the invoice containing the disputed Charge or the right to dispute the Charge will be waived.</p>
            <p>6.&nbsp;InTouch is entitled to invoice Subscriber, on a delayed basis, at any time after the Equipment has been returned or suspended from servie for any and all Usage Charges incurred prior to the termination of service, whether or not InTouch is aware of such charges at the time of the return of the Equipment.</p>
            <p>Form of Payment; Credit Card Charges and Authorization</p>
            <p>1.&nbsp;Unless otherwise agreed, Subscriber shall submit information from a U.S. based credit card (the "Credit Card") when ordering the Equipment and Service. Debit cards are not acceptable. The Credit Card will be charged the amount invoiced by InTouch automatically upon generation of an invoice. Subscriber authorizes InTouch to charge the Credit Card for all charges incurred hereunder.&nbsp;Additionally, InTouch may charge the Credit Card for Charges incurred prior to an invoice date if Charges exceed $250.00 during a billing period.</p>
            <p>2.&nbsp;InTouch may, in its sole discretion, accept non-U.S. credit card information from Subscriber, in which case InTouch will take a cash deposit via bank account debit or check in lieu of a credit card (the "Deposit"). The Deposit will be refunded after payment in full for all Charges incurred by Subscriber is received by InTouch. InTouch will not be liable for any fluctuation in exchange rates during the period in which a Deposit is held.</p>
            <p>3.&nbsp;By providing InTouch with the Credit Card account for payment, Subscriber represents that he or she is authorized to make charges on such account.</p>
            <p>4.&nbsp;Debit cards are not an acceptable form of payment.&nbsp;InTouch disclaims any and all liability for any damages incurred by Subscriber as a result of using a debit card, including, but not limited to, NSF charges.</p>
            <p>In the Event of Loss of the Equipment</p>
            <p>In the event the equipment is lost, Subscriber must notify InTouch immediately.&nbsp;Subscriber is responsible for all Usage Charges incurred on the Equipment up to the time that the provider/carrier contracted by InTouch to provide the Service disables the Equipment.</p>
            <p>Termination</p>
            <p>1.&nbsp;The use of the Equipment and all Service may be terminated or deactivated without notice by InTouch upon any of the following events: (a) InTouch has any reason to believe the Equipment was obtained by any misrepresentation or fraudulent means; (b) InTouch has any reason to believe any meter on the Equipment has been tampered with; (c) InTouch has any reason to believe the Equipment is or may be used for any illegal or improper purpose, or in violation of applicable laws; (d) a breach of any of these Terms and Conditions including the payment terms; or (e) detection of unusually high usage, or possible theft or fraud. InTouch may also terminate these Terms and Conditions without any liability whatsoever in the event that Service is not available to InTouch or becomes unavailable for any reason. No remedy of InTouch shall be exclusive of any other remedy whether provided herein or available at law or in equity, but shall be cumulative with other remedies.</p>
            <p>Applicable Law</p>
            <p>These Terms and Conditions shall be deemed entered into in Dallas County, Texas and shall be governed by the laws of the State of Texas. In addition, these Terms and Conditions are subject to applicable foreign, federal and state laws and tariffs.</p>
            <p>General</p>
            <p>1.&nbsp;These Terms and Conditions can only be modified by a writing signed by an officer of InTouch. Specifically, they cannot be modified by any InTouch representative over the phone or by email.</p>
            <p>2.&nbsp;The headings in these Terms and Conditions are for convenience of reference only and shall not affect the meaning or construction of the provisions contained herein.</p>
            <p>3.&nbsp;No waiver by InTouch of any breach of these Terms and Conditions shall be considered as a waiver of any subsequent breach of the same or any other provision hereof.</p>
            <p>4.&nbsp;Subscriber's rights and obligations under these Terms and Conditions cannot be assigned or transferred by Subscriber, nor can they be modified or waived except by written instrument signed by InTouch or its authorized agent. These Terms and Conditions constitute the entire agreement between InTouch and Subscriber; there are no other representations, conditions, warranties, guarantees, or collateral agreements, express or implied, statutory or otherwise, concerning the use of the Equipment or the Service, other than as set forth herein.</p>
            <p>5.&nbsp;InTouch is not liable for any lack of privacy which may be experienced with regard to the Service. Subscriber authorizes InTouch’s monitoring and recording of calls concerning Subscriber’s usage and the Service and consents to InTouch’s use of automatic dialing equipment to contact Subscriber. InTouch has the right to intercept and disclose transmissions in order to protect its rights or property and as requested by law enforcement authorities.</p>
            <p>6.&nbsp;If the performance of any part of these Terms and Conditions by InTouch is prevented, hindered, delayed or otherwise made impracticable by reason of any flood, riot, fire, judicial or governmental action, labor disputes, act of God, terrorist attack, or any other causes beyond the control of InTouch, InTouch shall be excused from performance to the extent that it is prevented, hindered or delayed by such causes.</p>
            <p>7.&nbsp;InTouch may assign all or part of its rights or duties under these Terms &amp; Conditions without the notice to Subscriber, except to the extent required by law. Such an assignment releases InTouch from all liability. Subscriber may not assign these Terms and Conditions without InTouch's prior written consent. Subject to these restrictions, these Terms and Conditions will bind the heirs, successors, and assigns of the respective parties who will receive its benefits.</p>
    </section>
</main>

<?php include 'tpl/footer.php' ?>